const localGameData =[
    {
        "NAME": "ARC Raiders",
        "PRICE": "39,99€",
        "PEGI": "16+",
        "GENRE": "Action",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP",
        "OS": "Windows 10 or later 64-bit (latest update)",
        "RAM": "12 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "NVIDIA GeForce GTX 1050 Ti",
        "GPU_1": "AMD Radeon RX 580",
        "GPU_2": "Intel Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6600K",
        "CPU_1": "AMD Ryzen R5 1600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Dead by Daylight",
        "PRICE": "69,99€",
        "PEGI": "18+",
        "GENRE": "Action",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP",
        "OS": "Windows 10 64-bit Operating System",
        "RAM": "8 GB RAM",
        "STORAGE": "50 GB available space",
        "GPU_0": "AMD HD 6850",
        "GPU_1": null,
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3-4170",
        "CPU_1": "AMD FX-8120",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "EA SPORTS FC™ 26",
        "PRICE": "0,99€",
        "PEGI": "12+",
        "GENRE": "Simulation, Sports",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP, Shared/Split Screen Co-op, Shared/Split Screen PvP, Single-player",
        "OS": "Windows 10/11 - 64-Bit (Latest Update).",
        "RAM": "8 GB RAM",
        "STORAGE": "100 GB available space",
        "GPU_0": "AMD RX 570",
        "GPU_1": "Nvidia GTX 1050 Ti",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 5 1600",
        "CPU_1": "Intel Core i5 6600k",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Grand Theft Auto V Enhanced",
        "PRICE": "14,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure, Racing",
        "MODE": "Online Co-op, Online PvP, Single-player",
        "OS": "Windows 10 (latest service pack)",
        "RAM": "8 GB RAM",
        "STORAGE": "105 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1630",
        "GPU_1": "AMD Radeon RX 6400",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i7-4770",
        "CPU_1": "AMD FX-9590",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Red Dead Redemption 2",
        "PRICE": "14,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure",
        "MODE": "Online Co-op, Online PvP, Single-player",
        "OS": "Windows 10 - 64-bit",
        "RAM": "8 GB RAM",
        "STORAGE": "150 GB available space",
        "GPU_0": "Nvidia GeForce GTX 770",
        "GPU_1": "AMD Radeon R9 280",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-2500K",
        "CPU_1": "AMD FX-6300",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Where Winds Meet",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, RPG",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP, Single-player",
        "OS": "Windows 10/11",
        "RAM": "16 GB RAM",
        "STORAGE": "100 GB available space",
        "GPU_0": "GTX 1060",
        "GPU_1": "RX 480",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Core i7-7700K",
        "CPU_1": "Ryzen 5 1600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "No Rest for the Wicked",
        "PRICE": "23,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure, RPG, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "16 GB RAM",
        "STORAGE": "46 GB available space",
        "GPU_0": "Nvidia GeForce GTX 1080",
        "GPU_1": "AMD Radeon 5600 XT",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-8400",
        "CPU_1": "AMD Ryzen 5 2600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Euro Truck Simulator 2",
        "PRICE": "19,99€",
        "PEGI": "N/A",
        "GENRE": "Indie, Simulation",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10 64-bit",
        "RAM": "8 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "NVIDIA GeForce GTX 660",
        "GPU_1": "AMD Radeon RX 460",
        "GPU_2": "Intel HD 630",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6400",
        "CPU_1": "AMD Ryzen 3 1200",
        "CPU_2": "similar",
        "CPU_3": null
    },
    {
        "NAME": "ARK: Survival Ascended",
        "PRICE": "44,99€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Indie, Massively Multiplayer, RPG, Early Access",
        "MODE": "Cross-Platform Multiplayer, LAN Co-op, LAN PvP, MMO, Online Co-op, Online PvP, Shared/Split Screen Co-op, Single-player",
        "OS": "Windows 10/11 with updates",
        "RAM": "16 GB RAM",
        "STORAGE": "180 GB available space",
        "GPU_0": "AMD Radeon RX 5600 XT",
        "GPU_1": "NVIDIA GeForce 1080",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 5 2600X",
        "CPU_1": "Intel Core i7-6800K",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Forza Horizon 5",
        "PRICE": "222,08€",
        "PEGI": "6+",
        "GENRE": "Action, Adventure, Racing, Simulation, Sports",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP, Single-player",
        "OS": "Windows 10 version 18362.0 or higher",
        "RAM": "8 GB RAM",
        "STORAGE": "110 GB available space",
        "GPU_0": "NVidia GTX 970",
        "GPU_1": "AMD RX 470",
        "GPU_2": "OR Intel Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel i5-4460",
        "CPU_1": "AMD Ryzen 3 1200",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Quarantine Zone: The Last Check",
        "PRICE": "19,99€",
        "PEGI": "16+",
        "GENRE": "Indie, Simulation, Strategy",
        "MODE": "Single-player",
        "OS": "Windows 10 x64 Bit",
        "RAM": "8 GB RAM",
        "STORAGE": "12 GB available space",
        "GPU_0": "GeForce GeForce GTX 980",
        "GPU_1": "Radeon RX 470",
        "GPU_2": "Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i7-5820K",
        "CPU_1": "AMD FX-8370",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Cult of the Lamb",
        "PRICE": "49,78€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, Indie, Strategy",
        "MODE": "Shared/Split Screen Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "4 GB RAM",
        "STORAGE": "4 GB available space",
        "GPU_0": "GeForce GTX 560 Ti",
        "GPU_1": "Radeon HD 7750",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3-3240",
        "CPU_1": "AMD FX-4300",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Baldur's Gate 3",
        "PRICE": "59,99€",
        "PEGI": "18+",
        "GENRE": "Adventure, RPG, Strategy",
        "MODE": "Cross-Platform Multiplayer, LAN Co-op, Online Co-op, Single-player",
        "OS": "Windows 10 64-bit",
        "RAM": "8 GB RAM",
        "STORAGE": "150 GB available space",
        "GPU_0": "Nvidia GTX 970",
        "GPU_1": "RX 480",
        "GPU_2": "Intel Arc A380",
        "GPU_3": "Qualcomm Adreno X1",
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel I5 4690",
        "CPU_1": "AMD FX 8350",
        "CPU_2": "Snapdragon X Elite",
        "CPU_3": null
    },
    {
        "NAME": "The Sims™ 4",
        "PRICE": "Free To Play",
        "PEGI": "6+",
        "GENRE": "Adventure, Casual, Simulation",
        "MODE": "Single-player",
        "OS": "Windows 10",
        "RAM": "4 GB RAM",
        "STORAGE": "26 GB available space",
        "GPU_0": "ATI Radeon X1300",
        "GPU_1": "Intel GMA X4500",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "4 threads)",
        "CPU_1": "AMD Ryzen 3 1200 3.1 GHz",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "HELLDIVERS™ 2",
        "PRICE": "39,99€",
        "PEGI": "16+",
        "GENRE": "Action",
        "MODE": "Online Co-op",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "135 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1050 Ti",
        "GPU_1": "AMD Radeon RX 470",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i7-4790K",
        "CPU_1": "AMD Ryzen 5 1500X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Battlefield™ 6",
        "PRICE": "69,99€",
        "PEGI": "18+",
        "GENRE": "Action",
        "MODE": "Cross-Platform Multiplayer, Online PvP, Single-player",
        "OS": "Windows 10",
        "RAM": "16 GB RAM",
        "STORAGE": "55 GB available space",
        "GPU_0": "Nvidia RTX 2060",
        "GPU_1": "AMD Radeon RX 5600 XT",
        "GPU_2": "Intel Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-8400",
        "CPU_1": "AMD Ryzen 5 2600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Enshrouded",
        "PRICE": "6,39€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, Indie, RPG, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "16 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD Radeon RX 580",
        "GPU_2": "Intel ARC A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6400",
        "CPU_1": "AMD Ryzen 5 1500X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Apex Legends™",
        "PRICE": "Free To Play",
        "PEGI": "16+",
        "GENRE": "Action, Adventure",
        "MODE": "Online Co-op, Online PvP",
        "OS": " Windows 10",
        "RAM": "6 GB RAM",
        "STORAGE": "75 GB available space",
        "GPU_0": "AMD Radeon HD 7790",
        "GPU_1": "NVIDIA GeForce GTX 950",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD FX 4350",
        "CPU_1": "Equivalent",
        "CPU_2": "Intel Core i3 6300",
        "CPU_3": "Equivalent"
    },
    {
        "NAME": "World of Warships",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Action, Massively Multiplayer, Simulation, Strategy",
        "MODE": "MMO, Online Co-op, Online PvP",
        "OS": "N/A",
        "RAM": "6 GB RAM",
        "STORAGE": "61 GB available space",
        "GPU_0": "1920×1080",
        "GPU_1": "NVIDIA GeForce GTX 770",
        "GPU_2": "AMD Radeon RX 570",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3-3210",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "PUBG: BATTLEGROUNDS",
        "PRICE": "Free To Play",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Massively Multiplayer",
        "MODE": "Online PvP",
        "OS": " Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "40 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 960",
        "GPU_1": "AMD Radeon R7 370",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-4430",
        "CPU_1": "AMD FX-6300",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "StarRupture",
        "PRICE": "19,99€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Indie, Simulation, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10 or later (64-Bit)",
        "RAM": "16 GB RAM",
        "STORAGE": "45 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD Radeon RX 580",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-8400",
        "CPU_1": "AMD Ryzen 5 2600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Fallout 76",
        "PRICE": "39,99€",
        "PEGI": "18+",
        "GENRE": "RPG",
        "MODE": "MMO, Online Co-op, Online PvP",
        "OS": "N/A",
        "RAM": "8 GB RAM",
        "STORAGE": "96 GB available space",
        "GPU_0": "NVIDIA GTX 780",
        "GPU_1": "AMD Radeon R9 285",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6600k",
        "CPU_1": "AMD Ryzen 3 1300X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Torchlight: Infinite",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, RPG",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "10 GB available space",
        "GPU_0": "Nvidia GTX 660Ti",
        "GPU_1": "AMD R9 270 with 2+ GB of VRAM",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5 2500",
        "CPU_1": "AMD FX-4350",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Path of Exile 2",
        "PRICE": "27,75€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure, Massively Multiplayer, RPG, Early Access",
        "MODE": "MMO, Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "100 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 960",
        "GPU_1": "Intel Arc A380",
        "GPU_2": "or ATI Radeon RX 470",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i7-7700",
        "CPU_1": "AMD Ryzen 5 2500x",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Farming Simulator 25",
        "PRICE": "29,99€",
        "PEGI": "N/A",
        "GENRE": "Simulation",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "45 GB available space",
        "GPU_0": "Nvidia GeForce GTX 1050Ti",
        "GPU_1": "AMD Radeon RX 470 (min",
        "GPU_2": "DX12 support)",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6400",
        "CPU_1": "AMD Ryzen 5 1400",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "CODE VEIN II",
        "PRICE": "69,99€",
        "PEGI": "12+",
        "GENRE": "Action, RPG",
        "MODE": "Single-player",
        "OS": "Windows 11",
        "RAM": "16 GB RAM",
        "STORAGE": "70 GB available space",
        "GPU_0": "Nvidia GeForce GTX 1660 Super",
        "GPU_1": "AMD Radeon RX 5700",
        "GPU_2": "Intel Arc B570",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-9600K",
        "CPU_1": "AMD Ryzen 5 3600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Tainted Grail: The Fall of Avalon",
        "PRICE": "19,63€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Indie, RPG",
        "MODE": "Single-player",
        "OS": "Windows 10 64-bit",
        "RAM": "12 GB RAM",
        "STORAGE": "31 GB available space",
        "GPU_0": "GTX 1060",
        "GPU_1": "AMD equivalent",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "i5 8th gen",
        "CPU_1": "AMD equivalent",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Black Desert",
        "PRICE": "9,99€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Massively Multiplayer, RPG, Strategy",
        "MODE": "MMO, Online Co-op, Online PvP",
        "OS": "Windows 10 (64-bit)",
        "RAM": "8 GB RAM",
        "STORAGE": "80 GB available space",
        "GPU_0": "GeForce GTX 970",
        "GPU_1": "Radeon RX 480",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Marvel Rivals",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Action",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP",
        "OS": "Windows 10 64-bit (1909 or newer)",
        "RAM": "16 GB RAM",
        "STORAGE": "70 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD RX 580",
        "GPU_2": "Intel Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6600K",
        "CPU_1": "AMD Ryzen 5 1600X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Crusader Kings III",
        "PRICE": "49,99€",
        "PEGI": "12+",
        "GENRE": "RPG, Simulation, Strategy",
        "MODE": "Online PvP, Single-player",
        "OS": "Windows® 10 Home 64 bit",
        "RAM": "8 GB RAM",
        "STORAGE": "20 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 660",
        "GPU_1": "AMD Radeon HD 7870",
        "GPU_2": "Intel Arc A310",
        "GPU_3": "Intel Iris Plus G7",
        "GPU_4": "AMD Radeon Vega 11",
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-750",
        "CPU_1": "AMD FX 4300",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Destiny 2",
        "PRICE": "Free To Play",
        "PEGI": "16+",
        "GENRE": "Action, Adventure",
        "MODE": "Online Co-op, Online PvP, Single-player",
        "OS": "Windows® 10 64-bit (latest Service Pack)",
        "RAM": "6 GB RAM",
        "STORAGE": "105 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 660",
        "GPU_1": "GTX 1050",
        "GPU_2": "AMD Radeon HD 7850",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3 3250",
        "CPU_1": "Intel Pentium G4560",
        "CPU_2": "AMD FX-4350",
        "CPU_3": null
    },
    {
        "NAME": "Dota 2",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Action, Strategy",
        "MODE": "Single-player",
        "OS": "macOS 10.15 or newer",
        "RAM": "4 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "NVIDIA GeForce 8600",
        "GPU_1": "9600GT",
        "GPU_2": "ATI",
        "GPU_3": "AMD Radeon HD2600",
        "GPU_4": "3600",
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Dual core from Intel",
        "CPU_1": "AMD at",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Dead by Daylight: Stranger Things Chapter 2",
        "PRICE": "11,99€",
        "PEGI": "18+",
        "GENRE": "Action",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP",
        "OS": "Windows 10 64-bit Operating System",
        "RAM": "8 GB RAM",
        "STORAGE": "50 GB available space",
        "GPU_0": "AMD HD 6850",
        "GPU_1": null,
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3-4170",
        "CPU_1": "AMD FX-8120",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "RV There Yet?",
        "PRICE": "7,79€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, Indie",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "3200 MB available space",
        "GPU_0": "NVidia 970",
        "GPU_1": null,
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Core i7-3820",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Rust",
        "PRICE": "39,99€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Indie, Massively Multiplayer, RPG",
        "MODE": "Cross-Platform Multiplayer, MMO, Online Co-op, Online PvP",
        "OS": "Windows 11",
        "RAM": "12 GB RAM",
        "STORAGE": "45 GB available space",
        "GPU_0": "AMD Radeon RX 470",
        "GPU_1": "NVIDIA GeForce GTX 1060",
        "GPU_2": "Intel Arc A580",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 5 1400",
        "CPU_1": "Intel Core i5-6600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Arena Breakout: Infinite",
        "PRICE": "Free To Play",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Massively Multiplayer, RPG, Strategy",
        "MODE": "MMO, Online Co-op, Online PvP",
        "OS": " Windows 10 or above",
        "RAM": "12 GB RAM",
        "STORAGE": "70 GB available space",
        "GPU_0": "NVIDIA GTX 960 2G",
        "GPU_1": "AMD Radeon RX 5500",
        "GPU_2": "Intel Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-7500",
        "CPU_1": "AMD Ryzen 5 1400",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Tom Clancy's Rainbow Six® Siege X",
        "PRICE": "Free To Play",
        "PEGI": "16+",
        "GENRE": "Action",
        "MODE": "Online Co-op, Online PvP, Single-player",
        "OS": "Windows 10, Windows 11 (64-bit versions)",
        "RAM": "8 GB RAM",
        "STORAGE": "65 GB available space",
        "GPU_0": "Nvidia GTX 1650",
        "GPU_1": "AMD RX 5500XT",
        "GPU_2": "Intel ARC A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 3 3100",
        "CPU_1": "Intel i3-8100",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Schedule I",
        "PRICE": "19,50€",
        "PEGI": "16+",
        "GENRE": "Action, Indie, Simulation, Strategy, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10 (64-bit)",
        "RAM": "8 GB RAM",
        "STORAGE": "8 GB available space",
        "GPU_0": "GeForce GTX 1060",
        "GPU_1": "Radeon RX 580",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "3GHz 4-Core",
        "CPU_1": "similar",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "SnowRunner",
        "PRICE": "183,41€",
        "PEGI": "N/A",
        "GENRE": "Adventure, Simulation",
        "MODE": "Online Co-op, Single-player",
        "OS": "macOS Sonoma",
        "RAM": "8 GB RAM",
        "STORAGE": "50 GB available space",
        "GPU_0": "GeForce GTX 660",
        "GPU_1": "Radeon R9 270",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel i3-4130",
        "CPU_1": "AMD Ryzen 3 2200U",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "ELDEN RING",
        "PRICE": "59,99€",
        "PEGI": "16+",
        "GENRE": "Action, RPG",
        "MODE": "Online Co-op, Online PvP, Single-player",
        "OS": "Windows 10",
        "RAM": "12 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "NVIDIA GEFORCE GTX 1060",
        "GPU_1": "AMD RADEON RX 580",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "INTEL CORE I5-8400",
        "CPU_1": "AMD RYZEN 3 3300X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Avatar: Frontiers of Pandora™",
        "PRICE": "29,99€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10/11 (64-bit versions)",
        "RAM": "16 GB RAM",
        "STORAGE": "90 GB available space",
        "GPU_0": "AMD RX 5700",
        "GPU_1": "Intel Arc A750 (",
        "GPU_2": "with ReBAR on)",
        "GPU_3": "NVIDIA GeForce GTX 1070",
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 5 3600 @",
        "CPU_1": "Intel Core i7-8700K @",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Dispatch",
        "PRICE": "28,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure, Casual, Indie, Strategy",
        "MODE": "Single-player",
        "OS": "Windows 10 (64-bit) or later",
        "RAM": "2 GB RAM",
        "STORAGE": "15 GB available space",
        "GPU_0": "NVIDIA GeForce GTX960",
        "GPU_1": "AMD Radeon RX560",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6402p CPU",
        "CPU_1": "AMD Ryzen 5 1600",
        "CPU_2": "higher",
        "CPU_3": null
    },
    {
        "NAME": "The Elder Scrolls® Online",
        "PRICE": "19,99€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Massively Multiplayer, RPG",
        "MODE": "MMO, Online Co-op, Online PvP",
        "OS": "Windows 10 64-bit",
        "RAM": "4 GB RAM",
        "STORAGE": "150 GB available space",
        "GPU_0": "AMD Radeon 6870)",
        "GPU_1": null,
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5 2300",
        "CPU_1": "AMD FX4350",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "World of Tanks",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Action, Massively Multiplayer, Simulation",
        "MODE": "MMO, Online PvP",
        "OS": "Windows 10 / 11 (64-bit only) with the latest updates",
        "RAM": "4 GB RAM",
        "STORAGE": "85 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 460",
        "GPU_1": "AMD Radeon HD 8770",
        "GPU_2": "1280x768 screen resolution",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-3330",
        "CPU_1": "AMD FX-6300",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Wuthering Waves",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, RPG",
        "MODE": "Single-player",
        "OS": "Windows10 64-bit",
        "RAM": "16 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD Radeon RX 570",
        "GPU_2": "Intel ARC A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5",
        "CPU_1": "Ryzen 2700",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Anno 117: Pax Romana",
        "PRICE": "59,99€",
        "PEGI": "12+",
        "GENRE": "Simulation, Strategy",
        "MODE": "Online Co-op, Online PvP, Single-player",
        "OS": "Windows 10 (64 bit only)",
        "RAM": "16 GB RAM",
        "STORAGE": "117 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1660",
        "GPU_1": "AMD Radeon RX-5600 XT",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 5 1600",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "ARC Raiders - The Bonecrown Set",
        "PRICE": "19,99€",
        "PEGI": "16+",
        "GENRE": "Action",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP",
        "OS": "Windows 10 or later 64-bit (latest update)",
        "RAM": "12 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "NVIDIA GeForce GTX 1050 Ti",
        "GPU_1": "AMD Radeon RX 580",
        "GPU_2": "Intel Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6600K",
        "CPU_1": "AMD Ryzen R5 1600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Cyberpunk 2077",
        "PRICE": "59,99€",
        "PEGI": "18+",
        "GENRE": "RPG",
        "MODE": "Single-player",
        "OS": " Windows 10",
        "RAM": "12 GB RAM",
        "STORAGE": "70 GB available space",
        "GPU_0": "GeForce GTX 1060",
        "GPU_1": "Radeon RX 580",
        "GPU_2": "Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Core i7-6700",
        "CPU_1": "Ryzen 5 1600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "NBA 2K26",
        "PRICE": "69,99€",
        "PEGI": "16+",
        "GENRE": "Sports",
        "MODE": "Online Co-op, Online PvP, Shared/Split Screen Co-op, Shared/Split Screen PvP, Single-player",
        "OS": "Windows 10 64-Bit (latest update)",
        "RAM": "8 GB RAM",
        "STORAGE": "110 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD Radeon RX 5500 XT",
        "GPU_2": "Intel Arc A580",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3-9100",
        "CPU_1": "AMD Ryzen 3 1200",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Cult of the Lamb: Woolhaven",
        "PRICE": "16,99€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, Indie, Strategy",
        "MODE": "Shared/Split Screen Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "4 GB RAM",
        "STORAGE": "4 GB available space",
        "GPU_0": "GeForce GTX 560 Ti",
        "GPU_1": "Radeon HD 7750",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3-3240",
        "CPU_1": "AMD FX-4300",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Kingdom Come: Deliverance II",
        "PRICE": "59,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure, RPG",
        "MODE": "Single-player",
        "OS": "Windows 10 64-bit (or newer)",
        "RAM": "16 GB RAM",
        "STORAGE": "100 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD Radeon RX 580",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-8400",
        "CPU_1": "AMD Ryzen 5 2600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "STAR WARS Jedi: Survivor™",
        "PRICE": "20,--€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure",
        "MODE": "Single-player",
        "OS": "Windows 10 64-bit",
        "RAM": "8 GB RAM",
        "STORAGE": "155 GB available space",
        "GPU_0": "GTX 1070",
        "GPU_1": "Radeon RX 580",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "4 core",
        "CPU_1": "8 threads",
        "CPU_2": "Intel Core i7-7700",
        "CPU_3": "Ryzen 5 1400"
    },
    {
        "NAME": "theHunter: Call of the Wild™",
        "PRICE": "19,50€",
        "PEGI": "12+",
        "GENRE": "Adventure, Simulation, Sports",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "4 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "NVIDIA GTX 660",
        "GPU_1": "ATI HD7870 -",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel i3-4170",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Hearts of Iron IV",
        "PRICE": "49,99€",
        "PEGI": "12+",
        "GENRE": "Simulation, Strategy",
        "MODE": "Cross-Platform Multiplayer, Single-player",
        "OS": "Windows® 10 Home 64 Bit",
        "RAM": "4 GB RAM",
        "STORAGE": "2 GB available space",
        "GPU_0": "Nvidia GeForce GTX 470",
        "GPU_1": "AMD HD 5850",
        "GPU_2": "Intel Iris Xe G7",
        "GPU_3": "AMD Radeon RX Vega 11",
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5 750",
        "CPU_1": "AMD FX 4300",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Diablo® IV",
        "PRICE": "49,99€",
        "PEGI": "16+",
        "GENRE": "Action, RPG",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Online PvP, Single-player",
        "OS": " Windows® 10 version 1909 or newer",
        "RAM": "8 GB RAM",
        "STORAGE": "90 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 660",
        "GPU_1": "Intel Arc A380",
        "GPU_2": "AMD Radeon R9 280",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-2500K",
        "CPU_1": "AMD FX-8350",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Microsoft Flight Simulator 2024",
        "PRICE": "79,99€",
        "PEGI": "N/A",
        "GENRE": "Simulation",
        "MODE": "Cross-Platform Multiplayer, Single-player",
        "OS": "Windows 10",
        "RAM": "16 GB RAM",
        "STORAGE": "50 GB available space",
        "GPU_0": "Radeon RX 5700",
        "GPU_1": "GeForce GTX 970",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 5 2600X",
        "CPU_1": "Intel Core i7-6800K",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "F1® 25",
        "PRICE": "59,99€",
        "PEGI": "N/A",
        "GENRE": "Racing, Simulation, Sports",
        "MODE": "Cross-Platform Multiplayer, LAN Co-op, LAN PvP, Online Co-op, Online PvP, Shared/Split Screen PvP, Single-player",
        "OS": "Windows 10 64-bit Version 21H1 or newer",
        "RAM": "8 GB RAM",
        "STORAGE": "100 GB available space",
        "GPU_0": "NVIDIA GTX 1060",
        "GPU_1": "GTX 1660Ti",
        "GPU_2": "RTX 2060",
        "GPU_3": "AMD RX 570",
        "GPU_4": "RX 590",
        "GPU_5": "6700XT",
        "GPU_6": "Intel Arc A380 (VR",
        "GPU_7": "RT)",
        "CPU_0": "Intel Core i5-6400",
        "CPU_1": "Core i5-9600k",
        "CPU_2": "AMD Ryzen 3 1200",
        "CPU_3": "Ryzen 5 2600X"
    },
    {
        "NAME": "Guild Wars 2®",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Adventure, Massively Multiplayer, RPG",
        "MODE": "MMO, Online Co-op, Online PvP",
        "OS": "N/A",
        "RAM": "8 GB RAM",
        "STORAGE": "70 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 680",
        "GPU_1": "AMD Radeon HD 7970",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel i3",
        "CPU_1": "AMD Athlon x4",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Forza Horizon 6",
        "PRICE": "69,99€",
        "PEGI": "N/A",
        "GENRE": "Racing, Simulation, Sports",
        "MODE": "Online Co-op, Online PvP, Single-player",
        "OS": "Windows 10 22H2 (version 19045) or higher",
        "RAM": "16 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "Nvidia GTX 1650",
        "GPU_1": "AMD RX 6500 XT",
        "GPU_2": "Intel Arc A380",
        "GPU_3": "Arc B390",
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel i5-8400",
        "CPU_1": "AMD Ryzen 5 1600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "ICARUS",
        "PRICE": "33,99€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, Simulation",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10 (64-bit versions)",
        "RAM": "16 GB RAM",
        "STORAGE": "70 GB available space",
        "GPU_0": "Nvidia GTX 1060",
        "GPU_1": null,
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel i5 8400",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Sons Of The Forest",
        "PRICE": "28,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure, Indie, Simulation",
        "MODE": "Online Co-op, Single-player",
        "OS": " Windows 10",
        "RAM": "12 GB RAM",
        "STORAGE": "20 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD Radeon RX 570",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "INTEL CORE I5-8400",
        "CPU_1": "AMD RYZEN 3 3300X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "R.E.P.O.",
        "PRICE": "9,49€",
        "PEGI": "16+",
        "GENRE": "Action, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "1 GB available space",
        "GPU_0": "GTX 970",
        "GPU_1": null,
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Core i5 6600",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "BeamNG.drive",
        "PRICE": "22,50€",
        "PEGI": "N/A",
        "GENRE": "Racing, Simulation, Early Access",
        "MODE": "Single-player",
        "OS": "BeamNG.",
        "RAM": "16 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "Nvidia GeForce GTX 1060)",
        "GPU_1": null,
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 5 1600",
        "CPU_1": "Intel Core i5 8400",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Once Human",
        "PRICE": "Free To Play",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, RPG, Simulation, Strategy",
        "MODE": "MMO, Online Co-op, Online PvP",
        "OS": "Windows 10 64-bit Operating System",
        "RAM": "8 GB RAM",
        "STORAGE": "90 GB available space",
        "GPU_0": "Nvidia GTX 750ti 4G",
        "GPU_1": "AMD Radeon RX550",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-4460",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Bellwright",
        "PRICE": "28,99€",
        "PEGI": "16+",
        "GENRE": "Action, RPG, Simulation, Strategy, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10 / Windows 11",
        "RAM": "16 GB RAM",
        "STORAGE": "24 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1070",
        "GPU_1": "AMD Radeon RX 580",
        "GPU_2": "Intel ARC A580",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-8600",
        "CPU_1": "AMD Ryzen 5 3600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "FINAL FANTASY XIV Online",
        "PRICE": "9,99€",
        "PEGI": "12+",
        "GENRE": "Massively Multiplayer, RPG",
        "MODE": "Cross-Platform Multiplayer, MMO, Online Co-op, Online PvP, Single-player",
        "OS": "Windows® 11 64 bit",
        "RAM": "8 GB RAM",
        "STORAGE": "140 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 970",
        "GPU_1": "higher",
        "GPU_2": "AMD Radeon RX 480",
        "GPU_3": "higher",
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Corei7-7700",
        "CPU_1": "higher",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Clair Obscur: Expedition 33",
        "PRICE": "49,99€",
        "PEGI": "16+",
        "GENRE": "Action, RPG",
        "MODE": "Single-player",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "55 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD Radeon RX 5600 XT",
        "GPU_2": "Intel Arc A380",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i7-8700K",
        "CPU_1": "AMD Ryzen 5 1600X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Phasmophobia",
        "PRICE": "13,65€",
        "PEGI": "16+",
        "GENRE": "Action, Indie, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "21 GB available space",
        "GPU_0": "NVIDIA GTX 970",
        "GPU_1": "AMD Radeon R9 390",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-4590",
        "CPU_1": "AMD Ryzen 5 2600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Disney Dreamlight Valley",
        "PRICE": "39,99€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, Casual, RPG, Simulation",
        "MODE": "Single-player",
        "OS": "Windows 10",
        "RAM": "6 GB RAM",
        "STORAGE": "15 GB available space",
        "GPU_0": "NVIDIA GeForce 9600 GT",
        "GPU_1": "512 MB",
        "GPU_2": "AMD Radeon HD 6570",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3-540",
        "CPU_1": "AMD Phenom II X4 940",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Warhammer 40,000: Darktide",
        "PRICE": "75,54€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure, RPG",
        "MODE": "Cross-Platform Multiplayer, Online Co-op",
        "OS": "Windows 10 (64 bit) / Windows 11 (64 bit)",
        "RAM": "8 GB RAM",
        "STORAGE": "72 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 970",
        "GPU_1": "AMD Radeon RX 570",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel i5-6600",
        "CPU_1": "AMD Ryzen 2400G",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Factorio",
        "PRICE": "Factorio Demo",
        "PEGI": "6+",
        "GENRE": "Casual, Indie, Simulation, Strategy",
        "MODE": "Cross-Platform Multiplayer, LAN Co-op, Online Co-op, Single-player",
        "OS": "Windows 11, 10",
        "RAM": "8 GB RAM",
        "STORAGE": "5 GB available space",
        "GPU_0": "Radeon R7 360",
        "GPU_1": "Intel UHD Graphics 730",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Quad core 3Ghz+",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Train Sim World® 6",
        "PRICE": "39,99€",
        "PEGI": "N/A",
        "GENRE": "Simulation",
        "MODE": "Single-player",
        "OS": " Windows 10 or Windows 11",
        "RAM": "8 GB RAM",
        "STORAGE": "35 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 750 Ti",
        "GPU_1": "AMD Radeon RX 460 with",
        "GPU_2": "more",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-4690 @",
        "CPU_1": "AMD Ryzen 5 1500X @",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "STAR WARS™: The Old Republic™",
        "PRICE": "Free To Play",
        "PEGI": "12+",
        "GENRE": "Massively Multiplayer, RPG",
        "MODE": "MMO",
        "OS": "Windows 10 or later – 64-bit",
        "RAM": "6 GB RAM",
        "STORAGE": "75 GB available space",
        "GPU_0": "AMD Radeon HD 7450",
        "GPU_1": "Nvidia GeForce 610",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core 2 Duo",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Titan Quest II",
        "PRICE": "3,99€",
        "PEGI": "16+",
        "GENRE": "Action, RPG, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10 / Windows 11",
        "RAM": "16 GB RAM",
        "STORAGE": "50 GB available space",
        "GPU_0": "AMD RX 6700 XT",
        "GPU_1": "NVIDIA GeForce RTX 2070",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-8600K",
        "CPU_1": "AMD Ryzen 5 2600X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Euro Truck Simulator 2 - Nordic Horizons",
        "PRICE": "17,99€",
        "PEGI": "N/A",
        "GENRE": "Indie, Simulation",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10 64-bit",
        "RAM": "8 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "NVIDIA GeForce GTX 660",
        "GPU_1": "AMD Radeon RX 460",
        "GPU_2": "Intel HD 630",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6400",
        "CPU_1": "AMD Ryzen 3 1200",
        "CPU_2": "similar",
        "CPU_3": null
    },
    {
        "NAME": "Half-Life: Alyx",
        "PRICE": "3,27€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure",
        "MODE": "Single-player",
        "OS": "Windows 10",
        "RAM": "12 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "GTX 1060",
        "GPU_1": "RX 580 -",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Core i5-7500",
        "CPU_1": "Ryzen 5 1600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Red Dead Redemption",
        "PRICE": "7,99€ / month",
        "PEGI": "18+",
        "GENRE": "Action",
        "MODE": "Single-player",
        "OS": "Windows 10 64-Bit",
        "RAM": "8 GB RAM",
        "STORAGE": "12 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 960",
        "GPU_1": "AMD Radeon R7 360",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-4670",
        "CPU_1": "AMD FX-9590",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "SILENT HILL f",
        "PRICE": "79,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure",
        "MODE": "Single-player",
        "OS": "Windows 11 x64",
        "RAM": "16 GB RAM",
        "STORAGE": "50 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1070 Ti",
        "GPU_1": "AMD Radeon RX 5700",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-8400",
        "CPU_1": "AMD Ryzen 5 2600",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Magic: The Gathering Arena",
        "PRICE": "Free To Play",
        "PEGI": "6+",
        "GENRE": "Strategy",
        "MODE": "Cross-Platform Multiplayer, Online PvP",
        "OS": "Windows 10",
        "RAM": "2 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "GeForce GTX 8800",
        "GPU_1": "Equivalent",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Equivalent",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "ELDEN RING NIGHTREIGN",
        "PRICE": "39,99€",
        "PEGI": "16+",
        "GENRE": "Action, RPG",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10",
        "RAM": "12 GB RAM",
        "STORAGE": "30 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 1060",
        "GPU_1": "AMD Radeon RX 580",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-10600",
        "CPU_1": "AMD RYZEN 5 5500",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "American Truck Simulator",
        "PRICE": "19,99€",
        "PEGI": "N/A",
        "GENRE": "Indie, Simulation",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows  10 64-bit",
        "RAM": "8 GB RAM",
        "STORAGE": "25 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 660",
        "GPU_1": "AMD Radeon RX 460",
        "GPU_2": "Intel HD 630",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6400",
        "CPU_1": "AMD Ryzen 3 1200",
        "CPU_2": "similar",
        "CPU_3": null
    },
    {
        "NAME": "Raft",
        "PRICE": "19,99€",
        "PEGI": "12+",
        "GENRE": "Adventure, Indie, Simulation",
        "MODE": "Online Co-op, Single-player",
        "OS": "N/A",
        "RAM": "6 GB RAM",
        "STORAGE": "10 GB available space",
        "GPU_0": "GeForce GTX 700 series",
        "GPU_1": "similar",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5",
        "CPU_1": "similar",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Foundation",
        "PRICE": "6,68€",
        "PEGI": "N/A",
        "GENRE": "Indie, Simulation, Strategy",
        "MODE": "Single-player",
        "OS": "Windows 10",
        "RAM": "8 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "GTX 960",
        "GPU_1": "R9 290 - 3 GB Video Memory",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-4460",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Ready or Not",
        "PRICE": "49,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure, Indie",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10, Windows 11",
        "RAM": "8 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 960",
        "GPU_1": "AMD Radeon R7 370",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-4430",
        "CPU_1": "AMD FX-6300",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Mount & Blade II: Bannerlord",
        "PRICE": "49,99€",
        "PEGI": "12+",
        "GENRE": "Action, Indie, RPG, Simulation, Strategy",
        "MODE": "Online PvP, Single-player",
        "OS": "Windows 10 (64-bit only)",
        "RAM": "6 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "Intel UHD Graphics 630",
        "GPU_1": "NVIDIA GeForce GTX 660",
        "GPU_2": "AMD Radeon HD 7850",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i3-8100",
        "CPU_1": "AMD Ryzen 3 1200",
        "CPU_2": "Snapdragon X Elite",
        "CPU_3": null
    },
    {
        "NAME": "Fallout 4",
        "PRICE": "19,99€",
        "PEGI": "18+",
        "GENRE": "RPG",
        "MODE": "Single-player",
        "OS": "N/A",
        "RAM": "8 GB RAM",
        "STORAGE": "30 GB available space",
        "GPU_0": "NVIDIA GTX 550 Ti",
        "GPU_1": "AMD Radeon HD 7870",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-2300",
        "CPU_1": "AMD Phenom II X4 945",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Grounded 2",
        "PRICE": "29,99€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, Early Access",
        "MODE": "Online Co-op, Single-player",
        "OS": "Windows 10/11 with updates",
        "RAM": "16 GB RAM",
        "STORAGE": "40 GB available space",
        "GPU_0": "AMD RX 5700",
        "GPU_1": "Nvidia GTX 1070",
        "GPU_2": "Intel Arc A580",
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "AMD Ryzen 5 2600",
        "CPU_1": "Intel i5-8400",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Resident Evil Requiem",
        "PRICE": "69,99€",
        "PEGI": "18+",
        "GENRE": "Action, Adventure",
        "MODE": "Single-player",
        "OS": "Windows 11",
        "RAM": "16 GB RAM",
        "STORAGE": "N/A",
        "GPU_0": "GeForce GTX 1660",
        "GPU_1": "Radeon RX 5500 XT",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel corei5-8500",
        "CPU_1": "AMD Ryzen 5 3500",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "PEAK",
        "PRICE": "7,49€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure, Indie",
        "MODE": "Online Co-op, Single-player",
        "OS": "Win 10",
        "RAM": "8 GB RAM",
        "STORAGE": "4 GB available space",
        "GPU_0": "GTX 1060",
        "GPU_1": "RX 6600 XT",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5 @",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "BALL x PIT",
        "PRICE": "6,39€",
        "PEGI": "6+",
        "GENRE": "Action, Indie",
        "MODE": "Single-player",
        "OS": "Windows 10 x64",
        "RAM": "8 GB RAM",
        "STORAGE": "600 MB available space",
        "GPU_0": "GeForce GTX 750",
        "GPU_1": "Radeon R7 260X",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-2500K",
        "CPU_1": "AMD Athlon X4 860K",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Split Fiction",
        "PRICE": "49,99€",
        "PEGI": "12+",
        "GENRE": "Action, Adventure",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Shared/Split Screen Co-op",
        "OS": "Windows 10/11",
        "RAM": "16 GB RAM",
        "STORAGE": "85 GB available space",
        "GPU_0": "NVIDIA GeForce GTX 970 -",
        "GPU_1": "Radeon RX 470 -",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-6600K",
        "CPU_1": "AMD Ryzen 5 2600X",
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "Satisfactory",
        "PRICE": "38,99€",
        "PEGI": "6+",
        "GENRE": "Adventure, Indie, Simulation, Strategy",
        "MODE": "Cross-Platform Multiplayer, Online Co-op, Single-player",
        "OS": "Windows 10 or later (64-Bit)",
        "RAM": "8 GB RAM",
        "STORAGE": "20 GB available space",
        "GPU_0": "Nvidia GTX 1650",
        "GPU_1": "GTX 1050-ti",
        "GPU_2": "or AMD RX 470",
        "GPU_3": "RX 570",
        "GPU_4": "performance & VRAM",
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "i5-3570 3.4 GHz 4 Core",
        "CPU_1": null,
        "CPU_2": null,
        "CPU_3": null
    },
    {
        "NAME": "ARK: Survival Evolved",
        "PRICE": "14,79€",
        "PEGI": "16+",
        "GENRE": "Action, Adventure, Indie, Massively Multiplayer, RPG",
        "MODE": "MMO, Single-player",
        "OS": "OSX 10.9 or Higher",
        "RAM": "8 GB RAM",
        "STORAGE": "60 GB available space",
        "GPU_0": "NVIDIA GTX 670",
        "GPU_1": "AMD Radeon HD 7870",
        "GPU_2": null,
        "GPU_3": null,
        "GPU_4": null,
        "GPU_5": null,
        "GPU_6": null,
        "GPU_7": null,
        "CPU_0": "Intel Core i5-2400",
        "CPU_1": "AMD FX-8320",
        "CPU_2": null,
        "CPU_3": null
    }
]